function testrig_AirOilPiston_test_config(mdl,testConfig,suspConfig)

% Select suspension setting
set_param([mdl '/Inputs'], 'popup_suspension_stiffness',suspConfig);

% Select load type
set_param([mdl '/Inputs'], 'popup_suspension_stiffness',suspConfig);

% Assume not a ride height test
set_param([mdl '/Inputs'], 'popup_rh_test_seq','None');

% Assume load is a mass
hasLoad = getSimulinkBlockHandle([mdl '/Load']) ~= -1;
if(hasLoad)
    set_param([mdl '/Load'],'popup_load_type','Mass');
end

switch lower(testConfig)
    case 'pulse'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','Pulse',...
            'pAmp','0.05',...
            'tPer','4',...
            'nCyc','50',...
            'nCycSet','1',...
            'cvd_value','1'...
            );
    case 'triangle'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','Triangle',...
            'pAmp','0.05',...
            'tPer','0.5',...
            'nCyc','50',...
            'nCycSet','10',...
            'cvd_value','1'...
            );
    case 'sine'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','Sine',...
            'pAmp','0.05',...
            'tPer','0.5',...
            'nCyc','50',...
            'nCycSet','10',...
            'cvd_value','1'...
            );
    case 'chirp'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','Chirp',...
            'pAmp','0.025',...
            'chirpFreqFinish','10',...
            'chirpFreqStart' ,'0.5',...
            'chirpTimeStart' ,'5',...
            'chirpTimeFinish','25',...
            'cvd_value','1'...
            );
    case 'none'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','None');
    case 'ride height'
        set_param([mdl '/Inputs'],...
            'popup_roadpz_test_type','None',...
            'popup_rh_test_seq','Pulse Sequence A');
    case 'extension triangle'
        if(hasLoad)
            set_param([mdl '/Inputs'],...
                'popup_roadpz_test_type','None',...
                'popup_rh_test_seq','None');
            set_param([mdl '/Load'],...
                'popup_load_type','Motion');
            set_param([mdl '/Load/Motion'], ...
                'popup_signalType','Triangle',...
                'tPer','3',...
                'pAmp','0.05');
        end
end