function quarter_car_msd_2x_config(mdl,testConfig)

switch lower(testConfig)
    case 'pulse'
        set_param([mdl '/Road Height'],...
            'popup_signalType','Pulse',...
            'pAmp','0.05',...
            'tPer','4',...
            'nCyc','50',...
            'nCycSet','1'...
            );
    case 'triangle'
        set_param([mdl '/Road Height'],...
            'popup_signalType','Triangle',...
            'pAmp','0.05',...
            'tPer','0.5',...
            'nCyc','50',...
            'nCycSet','10'...
            );
    case 'sine'
        set_param([mdl '/Road Height'],...
            'popup_signalType','Sine',...
            'pAmp','0.05',...
            'tPer','0.5',...
            'nCyc','50',...
            'nCycSet','10'...
            );
    case 'chirp'
        set_param([mdl '/Road Height'],...
            'popup_signalType','Chirp',...
            'pAmp','0.025',...
            'chirpFreqFinish','5',...
            'chirpFreqStart' ,'0.5',...
            'chirpTimeStart' ,'5',...
            'chirpTimeFinish','20'...
            );
    case 'rough'
        set_param([mdl '/Road Height'],...
            'popup_signalType','Rough',...
            'pAmp','1',...
            'spdkmh','10',...
            'roughTimeStart','5'...
            );
    case 'none'
        set_param([mdl '/Road Height'],...
            'popup_signalType','None');
end